<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Jagan" failures="6" tests="17" name="Test" time="29.3" errors="0" timestamp="2025-07-10T01:48:49 IST">
  <testcase classname="api.test.DataDrivenTests" name="testCreateUsers" time="4.391"/>
  <testcase classname="api.test.DataDrivenTests" name="testCreateUsers" time="1.186"/>
  <testcase classname="api.test.DataDrivenTests" name="testCreateUsers" time="1.149"/>
  <testcase classname="api.test.DataDrivenTests" name="testGetUsers" time="1.254"/>
  <testcase classname="api.test.DataDrivenTests" name="testGetUsers" time="1.188">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTests.testGetUsers(DataDrivenTests.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUsers -->
  <testcase classname="api.test.DataDrivenTests" name="testGetUsers" time="1.207"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUsers" time="1.201"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUsers" time="1.158"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUsers" time="1.21">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTests.testDeleteUsers(DataDrivenTests.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUsers -->
  <testcase classname="api.test.UserTests" name="testCreateUser" time="1.237"/>
  <testcase classname="api.test.UserTests" name="testGetUser" time="1.2">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testGetUser(UserTests.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUser -->
  <testcase classname="api.test.UserTests" name="testUpdateUser" time="3.444"/>
  <testcase classname="api.test.UserTests" name="testDeleteUser" time="1.207">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testDeleteUser(UserTests.java:86)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.StoreTests" name="testGetInventory" time="1.27"/>
  <testcase classname="api.test.StoreTests" name="testCreateOrder" time="1.2"/>
  <testcase classname="api.test.StoreTests" name="testGetOrder" time="1.241">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.StoreTests.testGetOrder(StoreTests.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetOrder -->
  <testcase classname="api.test.StoreTests" name="testDeleteOrder" time="1.261">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.StoreTests.testDeleteOrder(StoreTests.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteOrder -->
</testsuite> <!-- Test -->
